### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [is541-sibsutis/game-of-life#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:

1. В [wiki](https://github.com/is541-sibsutis/game-of-life/wiki) проекта написана статья с ТЗ.
1. В [issues](https://github.com/is541-sibsutis/game-of-life/issues) созданы задачи.
1. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by evgerher** [comment]
@evgeny-p Примерное ТЗ составлено.

**Comment by evgeny-p** [comment]
1. Касательно UX. Предлагается в первой версии ввод данных для первого поколения выполнять в интерактивном режиме. Кажется, это слишком трудозатратно даже для небольших поколений. Ручное тестирование такого приложения будет крайне трудоемким. Возможно, с самого начала стоит предусмотреть ввод из файла. В этом случае нужно в ТЗ описать формат входного файла. Начальное поколение можно задавать различными способами:
    1. Bitmap, где каждая клетка принимает значение «живая» или «мерткая». Наглядный формат.
    1. Координаты живых клеток. Компактный формат. Подходит для случая, когда живые клетки занимают менее половины поля.
    1. Координаты метрвых клеток. Подходит для обратого случая.

  Можно предусмотреть во входном файле поле, определяющее его формат, и реализовать все три предложенных варианта.

1. Не совсем ясно, о каких стандартных начальных параметрах идет речь в пункте «Аргументы командной строки». То, что обсуждалось выше — начальное поколение? Или параметры вроде скорости игры, количества поколений, что-то еще? Если второе, то формат конфига также нужно задокументировать.

1. Ручная установка значений клеток в графическом интерфейсе будет возможна только перед началом моделирования? Или во время паузы можно будет редактировать поле?

1. Оформление: в конце заголовков точки не ставятся.

После доработок ТЗ можно начинать заводить задачи.

**Comment by Detect1ve** [comment]
Принято решение отказаться от взаимодействия с командной строкой. Ваши замечания были учтены.
to: @evgeny-p

**Comment by evgeny-p** [comment]
> Принято решение отказаться от взаимодействия с командной строкой.

Почему?)
